-- Load 48 papers (39 PubMed + 9 Consensus) into knowledge_chunks
-- This migration is idempotent: existing papers won't be duplicated

BEGIN;

-- Insert 48 curated papers into knowledge_chunks
-- Papers already have embeddings from Gemini (768-dim vectors stored as jsonb)

INSERT INTO knowledge_chunks (slug, title, authors, year, source, url, topic, text, curated, created_at_ms)
VALUES
  -- PubMed Papers (1-39)
  ('stener-victorin-2024-pcos', 'Epigenetic inheritance of PCOS by developmental programming and germline transmission', 'Stener-Victorin E; Deng Q', 2024, 'Trends in Endocrinology & Metabolism', 'https://pubmed.ncbi.nlm.nih.gov/39732517/', 'comorbidities', 'Review on PCOS inheritance patterns - transgenerational effects - psychiatric comorbidities', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('broesen-2023-insulin-degludec', 'The Effect of Insulin Degludec Versus Insulin Glargine U100 on Glucose Metrics During CGM in T1D with Recurrent Nocturnal Hypoglycemia', 'Brøsen JMB; Agesen RM; et al.', 2023, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/37671755/', 'insulin_optimization', 'RCT comparing degludec vs glargine U100 in 74 adults with nocturnal hypo', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('hirsch-2024-dermis', 'The DERMIS Study: Methodologies - Results - and Implications for the Future', 'Hirsch IB; Khakpour D; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/39633523/', 'insulin_pump_technology', 'DERMIS Study analysis: histopathology of insulin infusion sets shows inflammation', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('moser-2024-aid-exercise', 'Use of AID around Physical Activity and Exercise in Type 1 Diabetes: EASD/ISPAD Position Statement', 'Moser O; Zaharieva D; et al.', 2024, 'Diabetes Care', 'https://pubmed.ncbi.nlm.nih.gov/39657609/', 'exercise', 'EASD/ISPAD position statement on AID systems during exercise', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('dekker-2024-minimed780g', 'Twelve-Month Real-World Use of Advanced Hybrid Closed-Loop System (MiniMed 780G)', 'Dekker P; van den Heuvel T; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/39465557/', 'closed_loop', 'Real-world MiniMed 780G: 481 PWD - HbA1c decreased 7.6% to 7.1%', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('karakus-2024-extended-hypo-hyper', 'Improvement in Extended Hypoglycemia and Extended Hyperglycemia With AID Initiation', 'Karakus KE; Snell-Bergeon J; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/39633524/', 'cgm_metrics', 'Retrospective: extended hypo/hyperglycemia metrics in 154 adults', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('andersen-2024-comorbidity', 'Machine Learning-Driven Prediction of Comorbidities and Mortality in Adults With T1D', 'Andersen JD; Stoltenberg CW; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/39091237/', 'comorbidities', 'Danish registry - 6572 adults. ML models predict CVD mortality within 5 years', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('stahl-2024-celiac', 'One-Year Outcomes Among Children Identified With Celiac Disease Through Mass Screening', 'Stahl MG; Pan Z; et al.', 2024, 'Clinical Gastroenterology and Hepatology', 'https://pubmed.ncbi.nlm.nih.gov/38615728/', 'comorbidities', 'ASK study in Colorado: 42 children with CD. Symptom improvement at 1-year', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('kusayev-2024-keto-cad', 'Low-Carbohydrate/Ketogenic Diet and Coronary Artery Disease: A Brief Review', 'Kusayev J; Weininger D; et al.', 2024, 'Current Cardiology Reports', 'https://pubmed.ncbi.nlm.nih.gov/38299850/', 'nutrition', 'Review: low-carb/ketogenic diet and CAD risk in diabetes', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('tschirhart-2024-distress', 'Prevalence and Correlates of Diabetes Distress in Pregnant Individuals', 'Tschirhart H; Usman Ali M; et al.', 2024, 'Diabetes Spectrum', 'https://pubmed.ncbi.nlm.nih.gov/40386816/', 'mental_health', '36 T1D + 40 T2D pregnant. 22.4% diabetes distress prevalence', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('senthil-kumar-2024-ctrp6', 'Exploring CTRP6: a biomarker and therapeutic target in metabolic diseases', 'Senthil Kumar J; Mehboob MZ; Lei X', 2024, 'American Journal of Physiology-Endocrinology and Metabolism', 'https://pubmed.ncbi.nlm.nih.gov/39701154/', 'biomarkers', 'Review: CTRP6 protein in T1D - T2D - PCOS - diabetic complications', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('liu-2024-insulin-glucocorticoid', 'Dynamic modeling of Insulin-Glucose-Glucocorticoid impulsive control system', 'Liu Y; Li C; Feng X; Dang T', 2024, 'Scientific Reports', 'https://pubmed.ncbi.nlm.nih.gov/39733115/', 'hormonal_interactions', 'Mathematical modeling: insulin-glucose-glucocorticoid system in T1D/T2D', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('rohilla-2024-caregivers', 'Barriers and Facilitators of T1D Management in Children: Socio-Cultural Enquiry', 'Rohilla L; Dayal D; et al.', 2024, 'Indian Journal of Community Medicine', 'https://pubmed.ncbi.nlm.nih.gov/39485313/', 'psychosocial', 'Qualitative (FGD) in India: 28 parents. Barriers and facilitators identified', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('lee-2024-cgm-disparities', 'Addressing Disparities Using CGM and Remote Patient Monitoring for Youth With T1D', 'Lee MY; Ritter V; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/39711469/', 'cgm', 'Pilot: CGM + RPM support for 91 youth. HbA1c decreased 9.8% to 9.0%', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('wong-2024-satisfaction', 'Diabetes Device Satisfaction Among Adolescents and Their Parents', 'Wong JJ; Alamarie SA; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/39529259/', 'technology_adoption', '175 adolescents + 176 parents. AID use higher satisfaction', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('madrid-victorin-2024-closed-loop-sleep', 'Closed-Loop Therapy and Sleep in Young People Newly Diagnosed With Type 1 Diabetes and Their Parents', 'Madrid-Victorin JJ; Scott EM; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/39397750/', 'sleep', 'RCT: 97 youth (mean age 12) at T1D diagnosis. 2-year follow-up', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('pham-2024-sleep-glycemic-variability', 'The association between glycaemic variability and sleep quality and quantity in adults with type 1 and type 2 diabetes: A systematic review', 'Pham CT; Ali A; et al.', 2024, 'Diabetic Medicine', 'https://pubmed.ncbi.nlm.nih.gov/39663626/', 'sleep', 'Systematic review (27 studies - 22 T1D). Sleep quality associated with glycemic variability', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('ljubicic-2024-parental-sleep', 'Sleep Quality and Evening Salivary Cortisol Levels in Association with the Psychological Resources of Parents of Children with Developmental Disorders and Type 1 Diabetes', 'Ljubičić M; Šare S; et al.', 2024, 'Journal of Autism and Developmental Disorders', 'https://pubmed.ncbi.nlm.nih.gov/38300504/', 'stress', 'Cross-sectional: 196 parents (40 with T1D children). Disrupted sleep impact', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('huang-2024-osa-diabetes', 'Association between obstructive sleep apnea syndrome and type1/type2 diabetes mellitus: A systematic review and meta-analysis', 'Huang H; Chen Z', 2024, 'Journal of Diabetes Investigation', 'https://pubmed.ncbi.nlm.nih.gov/39705149/', 'sleep', 'Meta-analysis (35 studies): Bidirectional OSA-diabetes link', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('sehgal-2023-diy-rtcgm', 'The Effect of Do-It-Yourself Real-Time Continuous Glucose Monitoring on Glycemic Variables and Participant-Reported Outcomes in Adults With Type 1 Diabetes: A Randomized Crossover Trial', 'Sehgal S; Elbalshy M; et al.', 2023, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/37671754/', 'cgm', 'Crossover: 52 adults. DIY rtCGM vs isCGM comparison. Cost-effective option', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('bayrak-demirel-2024-thyroid-insulin-paralysis', 'Thyrotoxic Hypokalemic Periodic Paralysis Induced by High-Dose Insulin in an Adolescent Male with Type 1 Diabetes Mellitus', 'Bayrak Demirel O; Koc C; et al.', 2024, 'Frontiers in Endocrinology', 'https://pubmed.ncbi.nlm.nih.gov/39719130/', 'comorbidities', 'Case: 17-year-old male with T1DM + Graves disease. Thyrotoxic hypokalemic periodic paralysis', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('menon-2024-antibody-negative-t1d', 'Characterisation of islet antibody-negative type 1 diabetes mellitus in Indian children', 'Menon JC; Singh P; et al.', 2024, 'Diabetic Medicine', 'https://pubmed.ncbi.nlm.nih.gov/39556519/', 'diagnosis', 'Multi-center India: 176 children. 15% antibody-negative T1D', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('mimouni-2024-magnesium-pregnancy', 'Unraveling the Magnesium Connection: The Cincinnati PPG'\''s Pioneering Work on Mineral Metabolism in Diabetes and Pregnancy', 'Mimouni FB; Khoury JC; et al.', 2024, 'Journal of Clinical Endocrinology & Metabolism', 'https://pubmed.ncbi.nlm.nih.gov/39117331/', 'pregnancy', 'Review: Maternal magnesium deficiency from poor glycemic control', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('lima-2024-myoinositol-dci', 'Imbalance of Myoinositol and D-Chiro-Inositol in Saliva of Children With Type-1 Diabetes Mellitus: A Cross-Sectional Study', 'Lima PHM; Cabral KSDS; et al.', 2024, 'Clinical Endocrinology', 'https://pubmed.ncbi.nlm.nih.gov/39555727/', 'biomarkers', 'Cross-sectional: 45 children (25 T1D). Elevated MI - reduced DCI ratio', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('ehrmann-2024-diabetes-logbook-app', 'Efficacy of a Digital Diabetes Logbook for People With Type 1, Type 2, and Gestational Diabetes: Results From a Multicenter, Randomized Controlled Trial', 'Ehrmann D; Hermanns N; et al.', 2024, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/38529954/', 'technology_adoption', 'RCT (424 PWD): mySugr PRO app vs standard care. Reduced diabetes distress', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('priesterroth-2024-mental-load', 'Counting the Minutes: Perceived Diabetes Mental Load and Its Associations With Technology Use and Mental Disorders', 'Priesterroth LS; Hermanns N; et al.', 2023, 'Journal of Diabetes Science and Technology', 'https://pubmed.ncbi.nlm.nih.gov/37981751/', 'mental_health', 'Survey (503 adults): Mental load higher in T1D vs T2D', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('barnard-kelly-2024-pro-consensus', 'Towards standardization of person-reported outcomes (PROs) in pediatric diabetes research: A consensus report', 'Barnard-Kelly K; Marrero D; et al.', 2024, 'Diabetic Medicine', 'https://pubmed.ncbi.nlm.nih.gov/39689218/', 'psychosocial', 'Consensus statement: 30+ experts on standardized PRO measures', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('vayisoglu-2024-parent-depression', 'Distinguishing risk factors for depression and burnout in parents managing type 1 diabetes mellitus in children', 'Vayisoglu SK; Koc E; Oncu E', 2024, 'Journal of Pediatric Nursing', 'https://pubmed.ncbi.nlm.nih.gov/39547076/', 'mental_health', 'Cross-sectional (140 parents): Burnout + depression predictors', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('hermanns-2024-symptoms-ecology', 'Somatic and mental symptoms associated with dysglycaemia, diabetes-related complications and mental conditions in people with diabetes: Assessments in daily life using continuous glucose monitoring and ecological momentary assessment', 'Hermanns N; Ehrmann D; et al.', 2024, 'Diabetes, Obesity & Metabolism', 'https://pubmed.ncbi.nlm.nih.gov/39375863/', 'mental_health', 'EMA + CGM (192 T1D + 179 T2D): Symptoms linked to glucose + mental health', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('mohr-2024-mydiamata-distress', 'Effectiveness of the MyDiaMate application in reducing diabetes distress in adults with type 1 diabetes: Study protocol of the multi-national, randomised-controlled MyREMEDY trial', 'Mohr TC; de Wit M; et al.', 2024, 'Diabetic Medicine', 'https://pubmed.ncbi.nlm.nih.gov/39350441/', 'mental_health', 'Protocol: 660 adults T1D. MyDiaMate app (CBT-based) vs care as usual', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('alzawahreh-2024-t1d-adolescent-empowerment', 'Improving Self-Efficacy, Quality of Life, and Glycemic Control in Adolescents With Type 1 Diabetes: Randomized Controlled Trial for the Evaluation of the Family-Centered Empowerment Model', 'Alzawahreh S; Ozturk C', 2024, 'JMIR Pediatrics and Parenting', 'https://pubmed.ncbi.nlm.nih.gov/39658013/', 'adolescent', 'RCT (68 Jordanian adolescents): Family-centered empowerment model', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('armentrout-2024-distress-cardiovascular', 'Emotional Distress and Cardiovascular Health in Young Adults with Type 1 Diabetes', 'Armentrout BL; Ahmed BH; et al.', 2024, 'Journal of Cardiovascular Development and Disease', 'https://pubmed.ncbi.nlm.nih.gov/39728281/', 'mental_health', 'Cross-sectional (165 young adults): Diabetes distress associated with lower cardiovascular health', true, EXTRACT(EPOCH FROM NOW()) * 1000),

  -- Consensus Papers (40-48)
  ('malone-2022-hcl-sleep', 'Use of a Hybrid Closed Loop Insulin Delivery System Improves Sleep and Glycemic Control in Adults with Long-Standing Type 1 Diabetes and Hypoglycemia Unawareness', 'S. Malone et al.', 2022, 'Sleep', 'https://consensus.app/papers/details/7ddbef9f70f15f07909e36929ee22eca/?utm_source=claude_code', 'sleep', '18-month HCL trial: improved sleep and hypoglycemia awareness', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('chakrabarti-2022-oracl-sleep', 'Closed-Loop Insulin Delivery Effects on Glycemia During Sleep and Sleep Quality in Older Adults with Type 1 Diabetes: Results from the ORACL Trial', 'Anindita Chakrabarti et al.', 2022, 'Diabetes Technology & Therapeutics', 'https://consensus.app/papers/details/cdb9667a866a59a497ff69d2d7576ace/?utm_source=claude_code', 'sleep', 'ORACL trial: closed-loop vs SAP: greater TIR but worse subjective sleep', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('sorensen-2026-aid-sleep-meta', 'The Effect of Automated Insulin Delivery Systems on Sleep Quality and Quantity in Type 1 Diabetes: A Systematic Review and Meta-Analysis', 'Michael Zaucha Sørensen et al.', 2026, 'Diabetes Technology & Therapeutics', 'https://consensus.app/papers/details/a741f54d90915979bd42ceb219a135e2/?utm_source=claude_code', 'sleep', 'Systematic review + meta-analysis of 27 studies on AID effects on sleep', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('snaith-2025-t1d-therapies', 'Advancing Type 1 Diabetes Management: Integrating Novel Therapies, Technologies, and Adjunctive Approaches', 'J. Snaith et al.', 2025, 'Diabetes Care', 'https://consensus.app/papers/details/e564745d34645a55be00dc87dbe9953a/?utm_source=claude_code', 'comorbidities', 'Review of synergy between technologies and adjunctive therapeutics in T1D', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('vessari-2026-findiconc', 'Demographic Change in Prevalent Type 1 Diabetes Adult Population, and Association of Risk Factors With Comorbidities and Mortality', 'H. Vessari et al.', 2026, 'Diabetes, Obesity & Metabolism', 'https://consensus.app/papers/details/0870821d104151d5bc6fe272be234a2d/?utm_source=claude_code', 'comorbidities', 'Finnish cohort (2014-2021): 35,574 adults. Aging population - improved HbA1c', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('sridhar-2023-t1d-ckd', 'Chronic kidney disease in type 1 diabetes: translation of novel type 2 diabetes therapeutics to individuals with type 1 diabetes', 'V. Sridhar et al.', 2023, 'Diabetologia', 'https://consensus.app/papers/details/db4094fd516c54b7b57963611b9b79a0/?utm_source=claude_code', 'comorbidities', 'Review of CKD management in T1D focusing on translating T2D therapeutics', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('franc-2025-emotional-distress', 'Emotional distress as a therapeutic target against persistent poor glycaemic control in subjects with type 1 diabetes: A systematic review', 'S. Franc et al.', 2025, 'Diabetes, Obesity & Metabolism', 'https://consensus.app/papers/details/db6cac6b8f05564887e35f0716db5fde/?utm_source=claude_code', 'mental_health', 'Systematic review of 24 studies on emotional distress and poor glycemic control', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('rodriguez-munoz-2024-t1d-distress', 'Type 1 diabetes-related distress: Current implications in care', 'Alba Rodríguez-Muñoz et al.', 2024, 'European Journal of Internal Medicine', 'https://consensus.app/papers/details/d494f2dff6d753849caf9a4dcb1f842e/?utm_source=claude_code', 'mental_health', 'Review of T1D-related distress as specific entity linked to glycemic control', true, EXTRACT(EPOCH FROM NOW()) * 1000),
  ('vargas-2024-latinx-mental-health', 'Mental Health and Glycemic Control Disparities among Latinx Adolescents with Type 1 Diabetes', 'Elizabeth Vargas et al.', 2024, 'Diabetes', 'https://consensus.app/papers/details/2a6a7c2716665d15b55479ff9dc44e2c/?utm_source=claude_code', 'mental_health', 'Observational: 84 Latinx vs 359 NHW youth. Latinx worse HbA1c + mental health outcomes', true, EXTRACT(EPOCH FROM NOW()) * 1000)
ON CONFLICT (slug) DO NOTHING;

-- Verify insertion
SELECT COUNT(*) as papers_loaded FROM knowledge_chunks;

COMMIT;
